### ISSUE TITLE
压缩时崩溃

### ISSUE THREAD

**Issue by jerry9433** [tangpeng/VideoCompressor#12]
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:355)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.IllegalArgumentException
    at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:76)
    at com.vincent.videocompressor.VideoController.a(SourceFile:251)
    at com.vincent.videocompressor.h$b.a(SourceFile:51)
    at com.vincent.videocompressor.h$b.doInBackground(SourceFile:32)
    at android.os.AsyncTask$2.call(AsyncTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ... 4 more
java.lang.IllegalArgumentException
    at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:76)
    at com.vincent.videocompressor.VideoController.a(SourceFile:251)
    at com.vincent.videocompressor.h$b.a(SourceFile:51)
    at com.vincent.videocompressor.h$b.doInBackground(SourceFile:32)
    at android.os.AsyncTask$2.call(AsyncTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:784)
```

**Comment by zanezha0** [comment]
亲测问题存在

**Comment by zippozeng** [comment]
权限问题

**Comment by mingongzi** [comment]
这个问题解决了吗？

**Comment by mingongzi** [comment]
> 问题

是权限的问题吗？怎么解决的
